# Generated by Django 6.1.1 on 2026-09-25 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('inProgress', 'In progress'), ('awaitFeedback', 'Await feedback'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(default='Technical Task', max_length=50)),
                ('assignees', models.JSONField(blank=True, default=list)),
                ('subtasks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
